name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # Run the workflow twice daily at 12:00 AM and 12:00 PM UTC
    - cron: "0 0,12 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Install Playwright browsers
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Run Playwright tests
      - name: Run Playwright tests
        run: npx playwright test
